# Generated by Django 3.1 on 2024-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_listed',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
