# Generated by Django 3.1 on 2024-04-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240427_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_refunded',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restock',
        ),
    ]
