# Generated by Django 3.1 on 2024-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='expected_date',
            field=models.DateField(null=True),
        ),
    ]
