# Generated by Django 3.1 on 2024-05-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_expected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
