# Generated by Django 3.1 on 2024-05-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20240505_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='address',
        ),
    ]
