# Generated by Django 3.1 on 2024-05-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderproduct_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='expected',
        ),
    ]
