# Generated by Django 3.1 on 2024-05-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderproduct_expected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='expected_date',
        ),
    ]
