# Generated by Django 3.1 on 2024-05-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20240514_1218'),
        ('orders', '0010_remove_orderproduct_expected_date'),
    ]

    operations = [
    ]
