# Generated by Django 3.1 on 2024-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_fld',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
