# Generated by Django 3.1 on 2024-02-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='otp_expiry',
        ),
    ]
