# Generated by Django 3.1 on 2024-02-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
