# Generated by Django 3.1 on 2024-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
