# Generated by Django 3.1 on 2024-03-01 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_otp_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
