# Generated by Django 3.1 on 2024-03-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240305_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_otp_attempt',
        ),
        migrations.RemoveField(
            model_name='account',
            name='otp_attempts',
        ),
    ]
