# Generated by Django 3.1 on 2024-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20240305_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp_fld',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
