# Generated by Django 3.1 on 2024-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20240305_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp_fld',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
