# Generated by Django 3.1 on 2024-03-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20240315_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
