# Generated by Django 3.1 on 2024-03-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_referral_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='referral_link',
        ),
    ]
