# Generated by Django 3.1 on 2024-03-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_account_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
