# Generated by Django 3.1 on 2024-03-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_account_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referral_link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
