# Generated by Django 3.1 on 2024-03-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20240318_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='referral_link',
        ),
    ]
